# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a403bb2b4c18e59a399a528bee29527c105fc32acd8230f6028f280d63d1d22d664a442308e340d00a0b76efb68ed747e89b6c3b645bccd8a0f5c91dc5ea8bb0

test:
  secret_key_base: a3702ddcee49881a57d8d9363e2542ec43b44d212cd40d24513188e4db2fe8fbc7a88e42b5fc4189e07c90a5833f9280a68941d708c95990455b763399aa40c4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
